grafana:
  image: grafana/grafana
  ports:
   - "3000:3000"
  volumes:
   - /home/sgolota/docker/monitoring/grafana/sqllite:/var/lib/grafana/
  links:
   - influx
   - graphite
sensu:
  image: sensu
  ports:
   # - "4567:4567"
   # - "6379:6379"
   - "5672:5672"
   - "4000:4000"
  volumes:
   - /home/sgolota/docker/monitoring/sensu/conf:/etc/sensu
  links:
   - influx
   - graphite
influx:
  image: influxdb
  # volumes:
   # - /home/sgolota/docker/graf_influx_comp/influxdb/conf:/config
  ports:
   - "8083:8083"
   - "8086:8086"
  expose:
   - "8090"
graphite:
  # image: testgraph
  image: ennexa/graphite
  volumes:
   - /home/sgolota/docker/graf_influx_comp/graphite/conf:/opt/graphite/conf
   - /home/sgolota/docker/graf_influx_comp/graphite/storage/whisper:/opt/graphite/storage/whisper
  ports:
   - "2003:2003"
   # - "8000:8000"
