grafana:
  image: grafana/grafana
  ports:
   - "3000:3000"
  volumes:
   - /srv/graphite/sqlite:/var/lib/grafana
   - /etc/localtime:/etc/localtime:ro
  links:
   - influx
   - graphite
sensu:
  image: sensu
  ports:
   - "4567:4567"
   - "6379:6379"
   - "5672:5672"
   - "4000:4000"
  volumes:
   # - /srv/sensu/config:/etc/sensu
   - /srv/sensu/config/conf.d:/etc/sensu/conf.d
   - /srv/sensu/config/handlers:/etc/sensu/handlers
  links:
   - influx
   - graphite
influx:
  image: influxdb
  # volumes:
   # - /home/sgolota/docker/graf_influx_comp/influxdb/conf:/config
  ports:
   - "8083:8083"
   - "8086:8086"
  expose:
   - "8090"
graphite:
  # image: testgraph
  image: ennexa/graphite
  volumes:
   - /srv/graphite/conf/:/opt/graphite/conf/ 
   - /srv/graphite/storage/whisper:/opt/graphite/storage/whisper
  ports:
   - "2003:2003"
   # - "8000:8000"
